In [1]:
!pip install matplotlib

%matplotlib inline

Requirement already satisfied: matplotlib in /Users/kosmas/.pyenv/versions/3.7.1/lib/python3.7/site-packages (3.1.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/kosmas/.pyenv/versions/3.7.1/lib/python3.7/site-packages (from matplotlib) (1.1.0)
Requirement already satisfied: cycler>=0.10 in /Users/kosmas/.pyenv/versions/3.7.1/lib/python3.7/site-packages (from matplotlib) (0.10.0)
Requirement already satisfied: numpy>=1.11 in /Users/kosmas/.pyenv/versions/3.7.1/lib/python3.7/site-packages (from matplotlib) (1.16.4)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /Users/kosmas/.pyenv/versions/3.7.1/lib/python3.7/site-packages (from matplotlib) (2.4.0)
Requirement already satisfied: python-dateutil>=2.1 in /Users/kosmas/.pyenv/versions/3.7.1/lib/python3.7/site-packages (from matplotlib) (2.8.0)
Requirement already satisfied: setuptools in /Users/kosmas/.pyenv/versions/3.7.1/lib/python3.7/site-packages (from kiwisolver>=1.0.1->matplotlib) (39.0.1)
Requirement already satisfied: six in /Users/kosmas/.pyenv/versions/3.7.1/lib/python3.7/site-packages (from cycler>=0.10->matplotlib) (1.12.0)

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_excel("/Users/kosmas/Desktop/Columbia_Data_Studio_Projects/data-studio-projects/Weekly projects/Fires_in Greece/DasikesPyrkagies2018v1.4.xlsx")
df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 22,ΟΧΗΜΑΤΑ,Unnamed: 24,Unnamed: 25,Unnamed: 26,ΕΝΑΕΡΙΑ,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31
0,Υπηρεσία,Νομός,Ημερ/νία Έναρξης,Ώρα Έναρξης,Ημερ/νία Κατασβεσης,Ώρα Κατάσβεσης,Δασαρχείο,Δήμος,Περιοχή,Διεύθυνση,...,ΑΛΛΕΣ ΔΥΝΑΜΕΙΣ,ΠΥΡΟΣ. ΟΧΗΜ.,ΟΧΗΜ. ΟΤΑ,ΒΥΤΙΟ- ΦΟΡΑ,ΜΗΧΑΝΗ-ΜΑΤΑ,ΕΛΙΚΟ- ΠΤΕΡΑ,Α/Φ CL415,Α/Φ CL215,Α/Φ PZL,Α/Φ GRU.
1,Π.Κ. ΚΑΛΑΜΟΥ,ΑΤΤΙΚΗΣ,2018-05-29 00:00:00,12:06,2018-05-29 00:00:00,18:30,NaN,Δ. ΩΡΩΠΟΥ,NaN,ΘΕΣΗ ΚΑΚΩΣΙ - ΒΛΑΣΤΟΣ,...,0,2,0,0,0,0,0,0,0,0
2,Π.Κ. ΚΑΛΑΜΟΥ,ΑΤΤΙΚΗΣ,2018-07-23 00:00:00,19:00,2018-07-31 00:00:00,10:18,NaN,Δ. ΩΡΩΠΟΥ,ΚΑΛΑΜΟΣ,ΟΛΥΜΠΙΚΑΣ Κ' ΔΕΞΑΜΕΝΗΣ ΑΝΩ ΠΑΝΟΡΑΜΑ-ΑΓ.ΑΠΟΣΤ,...,12,7,15,2,0,0,1,0,0,0
3,Π.Κ. ΚΑΛΑΜΟΥ,ΑΤΤΙΚΗΣ,2018-08-26 00:00:00,15:30,2018-08-27 00:00:00,07:55,NaN,Δ. ΩΡΩΠΟΥ,ΑΦΙΔΝΕΣ,ΑΦΙΔΝΑΙ,...,0,4,0,0,0,0,1,0,0,0
4,Π.Κ. ΚΑΛΑΜΟΥ,ΑΤΤΙΚΗΣ,2018-11-07 00:00:00,20:10,2018-11-08 00:00:00,21:10,NaN,Δ. ΩΡΩΠΟΥ,ΚΑΛΑΜΟΣ,ΘΕΣΗ ΑΓΙΑ ΤΡΙΑΔΑ-ΟΔΟΣ ΑΓΙΑΣ ΤΡΙΑΔΑΣ,...,5,3,6,1,2,0,0,0,0,0

In [4]:
pd.set_option('display.max_columns', None)

In [5]:
df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,ΚΑΜΜΕΝΗ ΕΚΤΑΣΗ (Σε Στρέμματα),Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,ΠΡΟΣΩΠΙΚΟ,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,ΟΧΗΜΑΤΑ,Unnamed: 24,Unnamed: 25,Unnamed: 26,ΕΝΑΕΡΙΑ,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31
0,Υπηρεσία,Νομός,Ημερ/νία Έναρξης,Ώρα Έναρξης,Ημερ/νία Κατασβεσης,Ώρα Κατάσβεσης,Δασαρχείο,Δήμος,Περιοχή,Διεύθυνση,Δάση,Δασική Έκταση,Άλση,Χορτ/κές Εκτάσεις,Καλάμια - Βάλτοι,Γεωργικές Εκτάσεις,Υπολλείματα Καλλιεργειών,Σκουπι-δότοποι,ΠΥΡΟΣ. ΣΩΜΑ,ΠΕΖΟΠΟΡΑ ΤΜΗΜΑΤΑ,ΕΘΕΛΟ-ΝΤΕΣ,ΣΤΡΑΤΟΣ,ΑΛΛΕΣ ΔΥΝΑΜΕΙΣ,ΠΥΡΟΣ. ΟΧΗΜ.,ΟΧΗΜ. ΟΤΑ,ΒΥΤΙΟ- ΦΟΡΑ,ΜΗΧΑΝΗ-ΜΑΤΑ,ΕΛΙΚΟ- ΠΤΕΡΑ,Α/Φ CL415,Α/Φ CL215,Α/Φ PZL,Α/Φ GRU.
1,Π.Κ. ΚΑΛΑΜΟΥ,ΑΤΤΙΚΗΣ,2018-05-29 00:00:00,12:06,2018-05-29 00:00:00,18:30,NaN,Δ. ΩΡΩΠΟΥ,NaN,ΘΕΣΗ ΚΑΚΩΣΙ - ΒΛΑΣΤΟΣ,0,0,0,0,0,3,0,0,6,0,2,0,0,2,0,0,0,0,0,0,0,0
2,Π.Κ. ΚΑΛΑΜΟΥ,ΑΤΤΙΚΗΣ,2018-07-23 00:00:00,19:00,2018-07-31 00:00:00,10:18,NaN,Δ. ΩΡΩΠΟΥ,ΚΑΛΑΜΟΣ,ΟΛΥΜΠΙΚΑΣ Κ' ΔΕΞΑΜΕΝΗΣ ΑΝΩ ΠΑΝΟΡΑΜΑ-ΑΓ.ΑΠΟΣΤ,0,150,0,150,0,350,0,0,21,6,30,0,12,7,15,2,0,0,1,0,0,0
3,Π.Κ. ΚΑΛΑΜΟΥ,ΑΤΤΙΚΗΣ,2018-08-26 00:00:00,15:30,2018-08-27 00:00:00,07:55,NaN,Δ. ΩΡΩΠΟΥ,ΑΦΙΔΝΕΣ,ΑΦΙΔΝΑΙ,0,0.1,0,0,0,0,0,0,15,1,26,0,0,4,0,0,0,0,1,0,0,0
4,Π.Κ. ΚΑΛΑΜΟΥ,ΑΤΤΙΚΗΣ,2018-11-07 00:00:00,20:10,2018-11-08 00:00:00,21:10,NaN,Δ. ΩΡΩΠΟΥ,ΚΑΛΑΜΟΣ,ΘΕΣΗ ΑΓΙΑ ΤΡΙΑΔΑ-ΟΔΟΣ ΑΓΙΑΣ ΤΡΙΑΔΑΣ,0,0,0,0,0,0,1.5,0,6,0,12,0,5,3,6,1,2,0,0,0,0,0

In [6]:
df.dtypes

Unnamed: 0                       object
Unnamed: 1                       object
Unnamed: 2                       object
Unnamed: 3                       object
Unnamed: 4                       object
Unnamed: 5                       object
Unnamed: 6                       object
Unnamed: 7                       object
Unnamed: 8                       object
Unnamed: 9                       object
ΚΑΜΜΕΝΗ ΕΚΤΑΣΗ (Σε Στρέμματα)    object
Unnamed: 11                      object
Unnamed: 12                      object
Unnamed: 13                      object
Unnamed: 14                      object
Unnamed: 15                      object
Unnamed: 16                      object
Unnamed: 17                      object
ΠΡΟΣΩΠΙΚΟ                        object
Unnamed: 19                      object
Unnamed: 20                      object
Unnamed: 21                      object
Unnamed: 22                      object
ΟΧΗΜΑΤΑ                          object
Unnamed: 24                      object
Unnamed: 25                      object
Unnamed: 26                      object
ΕΝΑΕΡΙΑ                          object
Unnamed: 28                      object
Unnamed: 29                      object
Unnamed: 30                      object
Unnamed: 31                      object
dtype: object

In [7]:
df.shape

(8007, 32)

In [8]:
df = df.rename(index=str, columns={'Unnamed: 2': 'Ημερνία_Εναρξης',
                                   'Unnamed: 4': 'Ημερνια_Κατασβεσης',
                                   'Unnamed: 0': 'Υρεσια',
                                   'Unnamed: 1': 'Νομός',
                                   'Unnamed: 3': 'ωρα_Έναρξης',
                                   'Unnamed: 5': 'ωρα_Κατάσβεσης',
                                   'ΚΑΜΜΕΝΗ ΕΚΤΑΣΗ (Σε Στρέμματα)': 'Καμμένες_Εκτάσεις',
                                   'Unnamed: 11': 'Δασική_Έκταση', 
                                   'Unnamed: 12': 'Άλση', 
                                   'Unnamed: 13': 'Χορτκές_Εκτάσεις',
                                   'Unnamed: 14': 'Καλάμια_Βάλτοι', 
                                   'Unnamed: 15': 'Γεωργικές_Εκτάσεις', 
                                   'Unnamed: 16': 'Υπολλείματα_Καλλιεργειών', 
                                   'Unnamed: 17': 'Σκουπιδότοποι',
                                   'ΠΡΟΣΩΠΙΚΟ': 'ΠΥΡΟΣ_ΣΩΜΑ',
                                   'Unnamed: 19': 'ΠΕΖΟΠΟΡΑ_ΤΜΗΜΑΤΑ',
                                   'Unnamed: 20': 'ΕΘΕΛΟ_ΝΤΕΣ',
                                   'Unnamed: 21': 'ΣΤΡΑΤΟΣ',
                                   'Unnamed: 22': 'ΑΛΛΕΣ_ΔΥΝΑΜΕΙΣ',
                                   'ΟΧΗΜΑΤΑ': 'ΠΥΡΟΣ_ΟΧΗΜ',
                                   'Unnamed: 24': 'ΟΧΗΜ_ΟΤΑ',
                                   'Unnamed: 25': 'ΒΥΤΙΟ_ΦΟΡΑ',
                                   'Unnamed: 26': 'ΜΗΧΑΝΗ_ΜΑΤΑ',
                                   'ΕΝΑΕΡΙΑ': 'ΕΛΙΚΟ_ΠΤΕΡΑ',
                                   'Unnamed: 28': 'Α_Φ_CL415',
                                   'Unnamed: 29': 'Α_Φ_CL215',
                                   'Unnamed: 30': 'Α_Φ_PZL',
                                   'Unnamed: 31': 'Α_Φ_GRU'})
df.head()

,Υρεσια,Νομός,Ημερνία_Εναρξης,ωρα_Έναρξης,Ημερνια_Κατασβεσης,ωρα_Κατάσβεσης,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Καμμένες_Εκτάσεις,Δασική_Έκταση,Άλση,Χορτκές_Εκτάσεις,Καλάμια_Βάλτοι,Γεωργικές_Εκτάσεις,Υπολλείματα_Καλλιεργειών,Σκουπιδότοποι,ΠΥΡΟΣ_ΣΩΜΑ,ΠΕΖΟΠΟΡΑ_ΤΜΗΜΑΤΑ,ΕΘΕΛΟ_ΝΤΕΣ,ΣΤΡΑΤΟΣ,ΑΛΛΕΣ_ΔΥΝΑΜΕΙΣ,ΠΥΡΟΣ_ΟΧΗΜ,ΟΧΗΜ_ΟΤΑ,ΒΥΤΙΟ_ΦΟΡΑ,ΜΗΧΑΝΗ_ΜΑΤΑ,ΕΛΙΚΟ_ΠΤΕΡΑ,Α_Φ_CL415,Α_Φ_CL215,Α_Φ_PZL,Α_Φ_GRU
0,Υπηρεσία,Νομός,Ημερ/νία Έναρξης,Ώρα Έναρξης,Ημερ/νία Κατασβεσης,Ώρα Κατάσβεσης,Δασαρχείο,Δήμος,Περιοχή,Διεύθυνση,Δάση,Δασική Έκταση,Άλση,Χορτ/κές Εκτάσεις,Καλάμια - Βάλτοι,Γεωργικές Εκτάσεις,Υπολλείματα Καλλιεργειών,Σκουπι-δότοποι,ΠΥΡΟΣ. ΣΩΜΑ,ΠΕΖΟΠΟΡΑ ΤΜΗΜΑΤΑ,ΕΘΕΛΟ-ΝΤΕΣ,ΣΤΡΑΤΟΣ,ΑΛΛΕΣ ΔΥΝΑΜΕΙΣ,ΠΥΡΟΣ. ΟΧΗΜ.,ΟΧΗΜ. ΟΤΑ,ΒΥΤΙΟ- ΦΟΡΑ,ΜΗΧΑΝΗ-ΜΑΤΑ,ΕΛΙΚΟ- ΠΤΕΡΑ,Α/Φ CL415,Α/Φ CL215,Α/Φ PZL,Α/Φ GRU.
1,Π.Κ. ΚΑΛΑΜΟΥ,ΑΤΤΙΚΗΣ,2018-05-29 00:00:00,12:06,2018-05-29 00:00:00,18:30,NaN,Δ. ΩΡΩΠΟΥ,NaN,ΘΕΣΗ ΚΑΚΩΣΙ - ΒΛΑΣΤΟΣ,0,0,0,0,0,3,0,0,6,0,2,0,0,2,0,0,0,0,0,0,0,0
2,Π.Κ. ΚΑΛΑΜΟΥ,ΑΤΤΙΚΗΣ,2018-07-23 00:00:00,19:00,2018-07-31 00:00:00,10:18,NaN,Δ. ΩΡΩΠΟΥ,ΚΑΛΑΜΟΣ,ΟΛΥΜΠΙΚΑΣ Κ' ΔΕΞΑΜΕΝΗΣ ΑΝΩ ΠΑΝΟΡΑΜΑ-ΑΓ.ΑΠΟΣΤ,0,150,0,150,0,350,0,0,21,6,30,0,12,7,15,2,0,0,1,0,0,0
3,Π.Κ. ΚΑΛΑΜΟΥ,ΑΤΤΙΚΗΣ,2018-08-26 00:00:00,15:30,2018-08-27 00:00:00,07:55,NaN,Δ. ΩΡΩΠΟΥ,ΑΦΙΔΝΕΣ,ΑΦΙΔΝΑΙ,0,0.1,0,0,0,0,0,0,15,1,26,0,0,4,0,0,0,0,1,0,0,0
4,Π.Κ. ΚΑΛΑΜΟΥ,ΑΤΤΙΚΗΣ,2018-11-07 00:00:00,20:10,2018-11-08 00:00:00,21:10,NaN,Δ. ΩΡΩΠΟΥ,ΚΑΛΑΜΟΣ,ΘΕΣΗ ΑΓΙΑ ΤΡΙΑΔΑ-ΟΔΟΣ ΑΓΙΑΣ ΤΡΙΑΔΑΣ,0,0,0,0,0,0,1.5,0,6,0,12,0,5,3,6,1,2,0,0,0,0,0

In [9]:
df.dtypes

Υρεσια                      object
Νομός                       object
Ημερνία_Εναρξης             object
ωρα_Έναρξης                 object
Ημερνια_Κατασβεσης          object
ωρα_Κατάσβεσης              object
Unnamed: 6                  object
Unnamed: 7                  object
Unnamed: 8                  object
Unnamed: 9                  object
Καμμένες_Εκτάσεις           object
Δασική_Έκταση               object
Άλση                        object
Χορτκές_Εκτάσεις            object
Καλάμια_Βάλτοι              object
Γεωργικές_Εκτάσεις          object
Υπολλείματα_Καλλιεργειών    object
Σκουπιδότοποι               object
ΠΥΡΟΣ_ΣΩΜΑ                  object
ΠΕΖΟΠΟΡΑ_ΤΜΗΜΑΤΑ            object
ΕΘΕΛΟ_ΝΤΕΣ                  object
ΣΤΡΑΤΟΣ                     object
ΑΛΛΕΣ_ΔΥΝΑΜΕΙΣ              object
ΠΥΡΟΣ_ΟΧΗΜ                  object
ΟΧΗΜ_ΟΤΑ                    object
ΒΥΤΙΟ_ΦΟΡΑ                  object
ΜΗΧΑΝΗ_ΜΑΤΑ                 object
ΕΛΙΚΟ_ΠΤΕΡΑ                 object
Α_Φ_CL415                   object
Α_Φ_CL215                   object
Α_Φ_PZL                     object
Α_Φ_GRU                     object
dtype: object

In [10]:
df = df.drop(['0'])

In [11]:
df.head()

,Υρεσια,Νομός,Ημερνία_Εναρξης,ωρα_Έναρξης,Ημερνια_Κατασβεσης,ωρα_Κατάσβεσης,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Καμμένες_Εκτάσεις,Δασική_Έκταση,Άλση,Χορτκές_Εκτάσεις,Καλάμια_Βάλτοι,Γεωργικές_Εκτάσεις,Υπολλείματα_Καλλιεργειών,Σκουπιδότοποι,ΠΥΡΟΣ_ΣΩΜΑ,ΠΕΖΟΠΟΡΑ_ΤΜΗΜΑΤΑ,ΕΘΕΛΟ_ΝΤΕΣ,ΣΤΡΑΤΟΣ,ΑΛΛΕΣ_ΔΥΝΑΜΕΙΣ,ΠΥΡΟΣ_ΟΧΗΜ,ΟΧΗΜ_ΟΤΑ,ΒΥΤΙΟ_ΦΟΡΑ,ΜΗΧΑΝΗ_ΜΑΤΑ,ΕΛΙΚΟ_ΠΤΕΡΑ,Α_Φ_CL415,Α_Φ_CL215,Α_Φ_PZL,Α_Φ_GRU
1,Π.Κ. ΚΑΛΑΜΟΥ,ΑΤΤΙΚΗΣ,2018-05-29 00:00:00,12:06,2018-05-29 00:00:00,18:30,NaN,Δ. ΩΡΩΠΟΥ,NaN,ΘΕΣΗ ΚΑΚΩΣΙ - ΒΛΑΣΤΟΣ,0,0,0,0,0,3,0,0,6,0,2,0,0,2,0,0,0,0,0,0,0,0
2,Π.Κ. ΚΑΛΑΜΟΥ,ΑΤΤΙΚΗΣ,2018-07-23 00:00:00,19:00,2018-07-31 00:00:00,10:18,NaN,Δ. ΩΡΩΠΟΥ,ΚΑΛΑΜΟΣ,ΟΛΥΜΠΙΚΑΣ Κ' ΔΕΞΑΜΕΝΗΣ ΑΝΩ ΠΑΝΟΡΑΜΑ-ΑΓ.ΑΠΟΣΤ,0,150,0,150,0,350,0,0,21,6,30,0,12,7,15,2,0,0,1,0,0,0
3,Π.Κ. ΚΑΛΑΜΟΥ,ΑΤΤΙΚΗΣ,2018-08-26 00:00:00,15:30,2018-08-27 00:00:00,07:55,NaN,Δ. ΩΡΩΠΟΥ,ΑΦΙΔΝΕΣ,ΑΦΙΔΝΑΙ,0,0.1,0,0,0,0,0,0,15,1,26,0,0,4,0,0,0,0,1,0,0,0
4,Π.Κ. ΚΑΛΑΜΟΥ,ΑΤΤΙΚΗΣ,2018-11-07 00:00:00,20:10,2018-11-08 00:00:00,21:10,NaN,Δ. ΩΡΩΠΟΥ,ΚΑΛΑΜΟΣ,ΘΕΣΗ ΑΓΙΑ ΤΡΙΑΔΑ-ΟΔΟΣ ΑΓΙΑΣ ΤΡΙΑΔΑΣ,0,0,0,0,0,0,1.5,0,6,0,12,0,5,3,6,1,2,0,0,0,0,0
5,1ος Π.Σ. ΑΘΗΝΩΝ,ΑΤΤΙΚΗΣ,2018-05-23 00:00:00,17:36,2018-05-23 00:00:00,18:10,ΠΕΝΤΕΛΗΣ,Δ. ΚΑΙΣΑΡΙΑΝΗΣ,NaN,ΤΕΡΜΑ ΟΔΟΥ ΚΑΡΑΜΟΛΕΓΚΟΥ (ΕΝΑΝΤΙ ΠΥΡΟΦΥΛΑΚΕΙΟΥ,0,10,0,0,0,0,0,0,13,0,10,0,0,5,4,0,0,0,0,0,0,0

In [12]:
df.shape

(8006, 32)

In [13]:
df = df.drop(columns=['Unnamed: 6','Unnamed: 8', 'Unnamed: 9'])

In [14]:
df.head()

,Υρεσια,Νομός,Ημερνία_Εναρξης,ωρα_Έναρξης,Ημερνια_Κατασβεσης,ωρα_Κατάσβεσης,Unnamed: 7,Καμμένες_Εκτάσεις,Δασική_Έκταση,Άλση,Χορτκές_Εκτάσεις,Καλάμια_Βάλτοι,Γεωργικές_Εκτάσεις,Υπολλείματα_Καλλιεργειών,Σκουπιδότοποι,ΠΥΡΟΣ_ΣΩΜΑ,ΠΕΖΟΠΟΡΑ_ΤΜΗΜΑΤΑ,ΕΘΕΛΟ_ΝΤΕΣ,ΣΤΡΑΤΟΣ,ΑΛΛΕΣ_ΔΥΝΑΜΕΙΣ,ΠΥΡΟΣ_ΟΧΗΜ,ΟΧΗΜ_ΟΤΑ,ΒΥΤΙΟ_ΦΟΡΑ,ΜΗΧΑΝΗ_ΜΑΤΑ,ΕΛΙΚΟ_ΠΤΕΡΑ,Α_Φ_CL415,Α_Φ_CL215,Α_Φ_PZL,Α_Φ_GRU
1,Π.Κ. ΚΑΛΑΜΟΥ,ΑΤΤΙΚΗΣ,2018-05-29 00:00:00,12:06,2018-05-29 00:00:00,18:30,Δ. ΩΡΩΠΟΥ,0,0,0,0,0,3,0,0,6,0,2,0,0,2,0,0,0,0,0,0,0,0
2,Π.Κ. ΚΑΛΑΜΟΥ,ΑΤΤΙΚΗΣ,2018-07-23 00:00:00,19:00,2018-07-31 00:00:00,10:18,Δ. ΩΡΩΠΟΥ,0,150,0,150,0,350,0,0,21,6,30,0,12,7,15,2,0,0,1,0,0,0
3,Π.Κ. ΚΑΛΑΜΟΥ,ΑΤΤΙΚΗΣ,2018-08-26 00:00:00,15:30,2018-08-27 00:00:00,07:55,Δ. ΩΡΩΠΟΥ,0,0.1,0,0,0,0,0,0,15,1,26,0,0,4,0,0,0,0,1,0,0,0
4,Π.Κ. ΚΑΛΑΜΟΥ,ΑΤΤΙΚΗΣ,2018-11-07 00:00:00,20:10,2018-11-08 00:00:00,21:10,Δ. ΩΡΩΠΟΥ,0,0,0,0,0,0,1.5,0,6,0,12,0,5,3,6,1,2,0,0,0,0,0
5,1ος Π.Σ. ΑΘΗΝΩΝ,ΑΤΤΙΚΗΣ,2018-05-23 00:00:00,17:36,2018-05-23 00:00:00,18:10,Δ. ΚΑΙΣΑΡΙΑΝΗΣ,0,10,0,0,0,0,0,0,13,0,10,0,0,5,4,0,0,0,0,0,0,0

In [15]:
df.shape

(8006, 29)

In [16]:
df = df.dropna()

In [17]:
df.shape

(6691, 29)

In [18]:
df['Ημερνία_Εναρξης'] = pd.to_datetime(df['Ημερνία_Εναρξης'])
df['Ημερνια_Κατασβεσης'] = pd.to_datetime(df['Ημερνια_Κατασβεσης'])
df['ωρα_Έναρξης'] = pd.to_datetime(df['ωρα_Έναρξης'])
df['ωρα_Κατάσβεσης'] = pd.to_datetime(df['ωρα_Κατάσβεσης'])

In [19]:
df.dtypes

Υρεσια                              object
Νομός                               object
Ημερνία_Εναρξης             datetime64[ns]
ωρα_Έναρξης                 datetime64[ns]
Ημερνια_Κατασβεσης          datetime64[ns]
ωρα_Κατάσβεσης              datetime64[ns]
Unnamed: 7                          object
Καμμένες_Εκτάσεις                   object
Δασική_Έκταση                       object
Άλση                                object
Χορτκές_Εκτάσεις                    object
Καλάμια_Βάλτοι                      object
Γεωργικές_Εκτάσεις                  object
Υπολλείματα_Καλλιεργειών            object
Σκουπιδότοποι                       object
ΠΥΡΟΣ_ΣΩΜΑ                          object
ΠΕΖΟΠΟΡΑ_ΤΜΗΜΑΤΑ                    object
ΕΘΕΛΟ_ΝΤΕΣ                          object
ΣΤΡΑΤΟΣ                             object
ΑΛΛΕΣ_ΔΥΝΑΜΕΙΣ                      object
ΠΥΡΟΣ_ΟΧΗΜ                          object
ΟΧΗΜ_ΟΤΑ                            object
ΒΥΤΙΟ_ΦΟΡΑ                          object
ΜΗΧΑΝΗ_ΜΑΤΑ                         object
ΕΛΙΚΟ_ΠΤΕΡΑ                         object
Α_Φ_CL415                           object
Α_Φ_CL215                           object
Α_Φ_PZL                             object
Α_Φ_GRU                             object
dtype: object

In [20]:
df['Καμμένες_Εκτάσεις'] = df['Καμμένες_Εκτάσεις'].astype(int)
df['Δασική_Έκταση'] = df['Δασική_Έκταση'].astype(int)
df['Άλση'] = df['Άλση'].astype(int)
df['Χορτκές_Εκτάσεις'] = df['Χορτκές_Εκτάσεις'].astype(int)
df['Καλάμια_Βάλτοι'] = df['Καλάμια_Βάλτοι'].astype(int)
df['Υπολλείματα_Καλλιεργειών'] = df['Υπολλείματα_Καλλιεργειών'].astype(int)
df['Σκουπιδότοποι'] = df['Σκουπιδότοποι'].astype(int)
df['ΠΥΡΟΣ_ΣΩΜΑ'] = df['ΠΥΡΟΣ_ΣΩΜΑ'].astype(int)
df['ΠΕΖΟΠΟΡΑ_ΤΜΗΜΑΤΑ'] = df['ΠΕΖΟΠΟΡΑ_ΤΜΗΜΑΤΑ'].astype(int)
df['ΕΘΕΛΟ_ΝΤΕΣ'] = df['ΕΘΕΛΟ_ΝΤΕΣ'].astype(int)
df['ΣΤΡΑΤΟΣ'] = df['ΣΤΡΑΤΟΣ'].astype(int)
df['ΑΛΛΕΣ_ΔΥΝΑΜΕΙΣ'] = df['ΑΛΛΕΣ_ΔΥΝΑΜΕΙΣ'].astype(int)
df['ΠΥΡΟΣ_ΟΧΗΜ'] = df['ΠΥΡΟΣ_ΟΧΗΜ'].astype(int)
df['ΟΧΗΜ_ΟΤΑ'] = df['ΟΧΗΜ_ΟΤΑ'].astype(int)
df['ΒΥΤΙΟ_ΦΟΡΑ'] = df['ΒΥΤΙΟ_ΦΟΡΑ'].astype(int)
df['ΜΗΧΑΝΗ_ΜΑΤΑ'] = df['ΜΗΧΑΝΗ_ΜΑΤΑ'].astype(int)
df['ΕΛΙΚΟ_ΠΤΕΡΑ'] = df['ΕΛΙΚΟ_ΠΤΕΡΑ'].astype(int)
df['ΜΗΧΑΝΗ_ΜΑΤΑ'] = df['ΜΗΧΑΝΗ_ΜΑΤΑ'].astype(int)
df['Α_Φ_CL415'] = df['Α_Φ_CL415'].astype(int)
df['Α_Φ_CL215'] = df['Α_Φ_CL215'].astype(int)
df['Α_Φ_PZL'] = df['Α_Φ_PZL'].astype(int)
df['Α_Φ_GRU'] = df['Α_Φ_GRU'].astype(int)

In [21]:
df.dtypes

Υρεσια                              object
Νομός                               object
Ημερνία_Εναρξης             datetime64[ns]
ωρα_Έναρξης                 datetime64[ns]
Ημερνια_Κατασβεσης          datetime64[ns]
ωρα_Κατάσβεσης              datetime64[ns]
Unnamed: 7                          object
Καμμένες_Εκτάσεις                    int64
Δασική_Έκταση                        int64
Άλση                                 int64
Χορτκές_Εκτάσεις                     int64
Καλάμια_Βάλτοι                       int64
Γεωργικές_Εκτάσεις                  object
Υπολλείματα_Καλλιεργειών             int64
Σκουπιδότοποι                        int64
ΠΥΡΟΣ_ΣΩΜΑ                           int64
ΠΕΖΟΠΟΡΑ_ΤΜΗΜΑΤΑ                     int64
ΕΘΕΛΟ_ΝΤΕΣ                           int64
ΣΤΡΑΤΟΣ                              int64
ΑΛΛΕΣ_ΔΥΝΑΜΕΙΣ                       int64
ΠΥΡΟΣ_ΟΧΗΜ                           int64
ΟΧΗΜ_ΟΤΑ                             int64
ΒΥΤΙΟ_ΦΟΡΑ                           int64
ΜΗΧΑΝΗ_ΜΑΤΑ                          int64
ΕΛΙΚΟ_ΠΤΕΡΑ                          int64
Α_Φ_CL415                            int64
Α_Φ_CL215                            int64
Α_Φ_PZL                              int64
Α_Φ_GRU                              int64
dtype: object

In [22]:
df['ώρα_σβησίματος'] = (df['ωρα_Κατάσβεσης'] - df['ωρα_Έναρξης'])

In [23]:
df['ημερες_σβησίματος'] = (df['Ημερνια_Κατασβεσης'] - df['Ημερνία_Εναρξης']).dt.days

In [24]:
df.head(10)

,Υρεσια,Νομός,Ημερνία_Εναρξης,ωρα_Έναρξης,Ημερνια_Κατασβεσης,ωρα_Κατάσβεσης,Unnamed: 7,Καμμένες_Εκτάσεις,Δασική_Έκταση,Άλση,Χορτκές_Εκτάσεις,Καλάμια_Βάλτοι,Γεωργικές_Εκτάσεις,Υπολλείματα_Καλλιεργειών,Σκουπιδότοποι,ΠΥΡΟΣ_ΣΩΜΑ,ΠΕΖΟΠΟΡΑ_ΤΜΗΜΑΤΑ,ΕΘΕΛΟ_ΝΤΕΣ,ΣΤΡΑΤΟΣ,ΑΛΛΕΣ_ΔΥΝΑΜΕΙΣ,ΠΥΡΟΣ_ΟΧΗΜ,ΟΧΗΜ_ΟΤΑ,ΒΥΤΙΟ_ΦΟΡΑ,ΜΗΧΑΝΗ_ΜΑΤΑ,ΕΛΙΚΟ_ΠΤΕΡΑ,Α_Φ_CL415,Α_Φ_CL215,Α_Φ_PZL,Α_Φ_GRU,ώρα_σβησίματος,ημερες_σβησίματος
1,Π.Κ. ΚΑΛΑΜΟΥ,ΑΤΤΙΚΗΣ,2018-05-29,2019-07-17 12:06:00,2018-05-29,2019-07-17 18:30:00,Δ. ΩΡΩΠΟΥ,0,0,0,0,0,3,0,0,6,0,2,0,0,2,0,0,0,0,0,0,0,0,06:24:00,0
2,Π.Κ. ΚΑΛΑΜΟΥ,ΑΤΤΙΚΗΣ,2018-07-23,2019-07-17 19:00:00,2018-07-31,2019-07-17 10:18:00,Δ. ΩΡΩΠΟΥ,0,150,0,150,0,350,0,0,21,6,30,0,12,7,15,2,0,0,1,0,0,0,-1 days +15:18:00,8
3,Π.Κ. ΚΑΛΑΜΟΥ,ΑΤΤΙΚΗΣ,2018-08-26,2019-07-17 15:30:00,2018-08-27,2019-07-17 07:55:00,Δ. ΩΡΩΠΟΥ,0,0,0,0,0,0,0,0,15,1,26,0,0,4,0,0,0,0,1,0,0,0,-1 days +16:25:00,1
4,Π.Κ. ΚΑΛΑΜΟΥ,ΑΤΤΙΚΗΣ,2018-11-07,2019-07-17 20:10:00,2018-11-08,2019-07-17 21:10:00,Δ. ΩΡΩΠΟΥ,0,0,0,0,0,0,1,0,6,0,12,0,5,3,6,1,2,0,0,0,0,0,01:00:00,1
5,1ος Π.Σ. ΑΘΗΝΩΝ,ΑΤΤΙΚΗΣ,2018-05-23,2019-07-17 17:36:00,2018-05-23,2019-07-17 18:10:00,Δ. ΚΑΙΣΑΡΙΑΝΗΣ,0,10,0,0,0,0,0,0,13,0,10,0,0,5,4,0,0,0,0,0,0,0,00:34:00,0
6,6ος Π.Σ. ΑΘΗΝΩΝ,ΑΤΤΙΚΗΣ,2018-03-13,2019-07-17 10:51:00,2018-03-13,2019-07-17 13:40:00,Δ. ΩΡΩΠΟΥ,0,0,0,0,0,0,0,0,13,0,21,0,14,4,0,1,0,0,0,0,0,0,02:49:00,0
7,6ος Π.Σ. ΑΘΗΝΩΝ,ΑΤΤΙΚΗΣ,2018-04-11,2019-07-17 16:21:00,2018-04-11,2019-07-17 17:15:00,Δ. ΔΙΟΝΥΣΟΥ,0,0,0,0,0,0,0,0,10,0,12,0,0,3,0,0,0,0,0,0,0,0,00:54:00,0
8,6ος Π.Σ. ΑΘΗΝΩΝ,ΑΤΤΙΚΗΣ,2018-07-25,2019-07-17 15:50:00,2018-07-25,2019-07-17 20:15:00,Δ. ΑΧΑΡΝΩΝ,0,0,0,0,0,0,0,0,9,0,0,0,0,3,0,0,0,0,0,0,0,0,04:25:00,0
9,6ος Π.Σ. ΑΘΗΝΩΝ,ΑΤΤΙΚΗΣ,2018-09-01,2019-07-17 22:29:00,2018-09-02,2019-07-17 00:00:00,Δ. ΑΧΑΡΝΩΝ,0,0,0,0,0,0,0,0,18,0,0,0,0,7,0,0,0,0,0,0,0,0,-1 days +01:31:00,1
10,6ος Π.Σ. ΑΘΗΝΩΝ,ΑΤΤΙΚΗΣ,2018-09-08,2019-07-17 14:53:00,2018-09-08,2019-07-17 14:53:00,Δ. ΔΙΟΝΥΣΟΥ,0,0,0,0,0,0,0,0,2,0,10,0,0,1,0,0,0,0,0,0,0,0,00:00:00,0

In [25]:
df['Σύνολο_καμμένων'] = df.apply(lambda row: row.Καμμένες_Εκτάσεις + row.Δασική_Έκταση + row.Άλση + row.Χορτκές_Εκτάσεις + row.Καλάμια_Βάλτοι + row.Γεωργικές_Εκτάσεις + row.Υπολλείματα_Καλλιεργειών + row.Σκουπιδότοποι, axis=1)

In [26]:
df.head()

,Υρεσια,Νομός,Ημερνία_Εναρξης,ωρα_Έναρξης,Ημερνια_Κατασβεσης,ωρα_Κατάσβεσης,Unnamed: 7,Καμμένες_Εκτάσεις,Δασική_Έκταση,Άλση,Χορτκές_Εκτάσεις,Καλάμια_Βάλτοι,Γεωργικές_Εκτάσεις,Υπολλείματα_Καλλιεργειών,Σκουπιδότοποι,ΠΥΡΟΣ_ΣΩΜΑ,ΠΕΖΟΠΟΡΑ_ΤΜΗΜΑΤΑ,ΕΘΕΛΟ_ΝΤΕΣ,ΣΤΡΑΤΟΣ,ΑΛΛΕΣ_ΔΥΝΑΜΕΙΣ,ΠΥΡΟΣ_ΟΧΗΜ,ΟΧΗΜ_ΟΤΑ,ΒΥΤΙΟ_ΦΟΡΑ,ΜΗΧΑΝΗ_ΜΑΤΑ,ΕΛΙΚΟ_ΠΤΕΡΑ,Α_Φ_CL415,Α_Φ_CL215,Α_Φ_PZL,Α_Φ_GRU,ώρα_σβησίματος,ημερες_σβησίματος,Σύνολο_καμμένων
1,Π.Κ. ΚΑΛΑΜΟΥ,ΑΤΤΙΚΗΣ,2018-05-29,2019-07-17 12:06:00,2018-05-29,2019-07-17 18:30:00,Δ. ΩΡΩΠΟΥ,0,0,0,0,0,3,0,0,6,0,2,0,0,2,0,0,0,0,0,0,0,0,06:24:00,0,3.0
2,Π.Κ. ΚΑΛΑΜΟΥ,ΑΤΤΙΚΗΣ,2018-07-23,2019-07-17 19:00:00,2018-07-31,2019-07-17 10:18:00,Δ. ΩΡΩΠΟΥ,0,150,0,150,0,350,0,0,21,6,30,0,12,7,15,2,0,0,1,0,0,0,-1 days +15:18:00,8,650.0
3,Π.Κ. ΚΑΛΑΜΟΥ,ΑΤΤΙΚΗΣ,2018-08-26,2019-07-17 15:30:00,2018-08-27,2019-07-17 07:55:00,Δ. ΩΡΩΠΟΥ,0,0,0,0,0,0,0,0,15,1,26,0,0,4,0,0,0,0,1,0,0,0,-1 days +16:25:00,1,0.0
4,Π.Κ. ΚΑΛΑΜΟΥ,ΑΤΤΙΚΗΣ,2018-11-07,2019-07-17 20:10:00,2018-11-08,2019-07-17 21:10:00,Δ. ΩΡΩΠΟΥ,0,0,0,0,0,0,1,0,6,0,12,0,5,3,6,1,2,0,0,0,0,0,01:00:00,1,1.0
5,1ος Π.Σ. ΑΘΗΝΩΝ,ΑΤΤΙΚΗΣ,2018-05-23,2019-07-17 17:36:00,2018-05-23,2019-07-17 18:10:00,Δ. ΚΑΙΣΑΡΙΑΝΗΣ,0,10,0,0,0,0,0,0,13,0,10,0,0,5,4,0,0,0,0,0,0,0,00:34:00,0,10.0

In [27]:
df.shape

(6691, 32)

In [28]:
df.dtypes

Υρεσια                               object
Νομός                                object
Ημερνία_Εναρξης              datetime64[ns]
ωρα_Έναρξης                  datetime64[ns]
Ημερνια_Κατασβεσης           datetime64[ns]
ωρα_Κατάσβεσης               datetime64[ns]
Unnamed: 7                           object
Καμμένες_Εκτάσεις                     int64
Δασική_Έκταση                         int64
Άλση                                  int64
Χορτκές_Εκτάσεις                      int64
Καλάμια_Βάλτοι                        int64
Γεωργικές_Εκτάσεις                   object
Υπολλείματα_Καλλιεργειών              int64
Σκουπιδότοποι                         int64
ΠΥΡΟΣ_ΣΩΜΑ                            int64
ΠΕΖΟΠΟΡΑ_ΤΜΗΜΑΤΑ                      int64
ΕΘΕΛΟ_ΝΤΕΣ                            int64
ΣΤΡΑΤΟΣ                               int64
ΑΛΛΕΣ_ΔΥΝΑΜΕΙΣ                        int64
ΠΥΡΟΣ_ΟΧΗΜ                            int64
ΟΧΗΜ_ΟΤΑ                              int64
ΒΥΤΙΟ_ΦΟΡΑ                            int64
ΜΗΧΑΝΗ_ΜΑΤΑ                           int64
ΕΛΙΚΟ_ΠΤΕΡΑ                           int64
Α_Φ_CL415                             int64
Α_Φ_CL215                             int64
Α_Φ_PZL                               int64
Α_Φ_GRU                               int64
ώρα_σβησίματος              timedelta64[ns]
ημερες_σβησίματος                     int64
Σύνολο_καμμένων                     float64
dtype: object

In [29]:
df = df.rename(index=str, columns={'Υρεσια': 'Fire_department',
                                   'Νομός': 'region',
                                   'Ημερνία_Εναρξης': 'start_date',
                                   'ωρα_Έναρξης': 'start_time',
                                   'Ημερνια_Κατασβεσης': 'end_date',
                                   'ωρα_Κατάσβεσης': 'end_time',
                                   'Unnamed: 7': 'borough',
                                   'Καμμένες_Εκτάσεις':'burned_forests1',
                                   'Δασική_Έκταση':'burned_forests2', 
                                   'Άλση':'burned_forests3', 
                                   'Χορτκές_Εκτάσεις':'burned_fields',
                                   'Καλάμια_Βάλτοι':'burned_swamp', 
                                   'Γεωργικές_Εκτάσεις':'burned_Agricultural', 
                                   'Υπολλείματα_Καλλιεργειών':'burned_Agricultural2', 
                                   'Σκουπιδότοποι':'burned_garbage_disposal_sites',
                                   'ΠΥΡΟΣ_ΣΩΜΑ':'firefighters',
                                   'ΠΕΖΟΠΟΡΑ_ΤΜΗΜΑΤΑ':'firefighters2',
                                   'ΕΘΕΛΟ_ΝΤΕΣ':'volunt_firefighters',
                                   'ΣΤΡΑΤΟΣ':'military_forces',
                                   'ΑΛΛΕΣ_ΔΥΝΑΜΕΙΣ':'other_forces',
                                   'ΠΥΡΟΣ_ΟΧΗΜ':'Fire_trucks',
                                   'ΟΧΗΜ_ΟΤΑ':'other_fire_vehicles',
                                   'ΒΥΤΙΟ_ΦΟΡΑ':'fire_tankers',
                                   'ΜΗΧΑΝΗ_ΜΑΤΑ':'fire_equipent',
                                   'ΕΛΙΚΟ_ΠΤΕΡΑ':'helicopters',
                                   'Α_Φ_CL415':'fire_plane_type1',
                                   'Α_Φ_CL215':'fire_plane_type2',
                                   'Α_Φ_PZL':'fire_plane_type3',
                                   'Α_Φ_GRU':'fire_plane_type4',
                                  'ώρα_σβησίματος':'extinguish_time',
                                  'ημερες_σβησίματος':'extinguish_date',
                                  'Σύνολο_καμμένων': 'total_burned_acres'})
df.head()

,Fire_department,region,start_date,start_time,end_date,end_time,borough,burned_forests1,burned_forests2,burned_forests3,burned_fields,burned_swamp,burned_Agricultural,burned_Agricultural2,burned_garbage_disposal_sites,firefighters,firefighters2,volunt_firefighters,military_forces,other_forces,Fire_trucks,other_fire_vehicles,fire_tankers,fire_equipent,helicopters,fire_plane_type1,fire_plane_type2,fire_plane_type3,fire_plane_type4,extinguish_time,extinguish_date,total_burned_acres
1,Π.Κ. ΚΑΛΑΜΟΥ,ΑΤΤΙΚΗΣ,2018-05-29,2019-07-17 12:06:00,2018-05-29,2019-07-17 18:30:00,Δ. ΩΡΩΠΟΥ,0,0,0,0,0,3,0,0,6,0,2,0,0,2,0,0,0,0,0,0,0,0,06:24:00,0,3.0
2,Π.Κ. ΚΑΛΑΜΟΥ,ΑΤΤΙΚΗΣ,2018-07-23,2019-07-17 19:00:00,2018-07-31,2019-07-17 10:18:00,Δ. ΩΡΩΠΟΥ,0,150,0,150,0,350,0,0,21,6,30,0,12,7,15,2,0,0,1,0,0,0,-1 days +15:18:00,8,650.0
3,Π.Κ. ΚΑΛΑΜΟΥ,ΑΤΤΙΚΗΣ,2018-08-26,2019-07-17 15:30:00,2018-08-27,2019-07-17 07:55:00,Δ. ΩΡΩΠΟΥ,0,0,0,0,0,0,0,0,15,1,26,0,0,4,0,0,0,0,1,0,0,0,-1 days +16:25:00,1,0.0
4,Π.Κ. ΚΑΛΑΜΟΥ,ΑΤΤΙΚΗΣ,2018-11-07,2019-07-17 20:10:00,2018-11-08,2019-07-17 21:10:00,Δ. ΩΡΩΠΟΥ,0,0,0,0,0,0,1,0,6,0,12,0,5,3,6,1,2,0,0,0,0,0,01:00:00,1,1.0
5,1ος Π.Σ. ΑΘΗΝΩΝ,ΑΤΤΙΚΗΣ,2018-05-23,2019-07-17 17:36:00,2018-05-23,2019-07-17 18:10:00,Δ. ΚΑΙΣΑΡΙΑΝΗΣ,0,10,0,0,0,0,0,0,13,0,10,0,0,5,4,0,0,0,0,0,0,0,00:34:00,0,10.0

In [30]:
df.to_csv('data_fire.csv')

In [31]:
df.shape

(6691, 32)

In [32]:
df['total_firefight_personel'] = df.apply(lambda row: row.firefighters + row.firefighters2 + row.volunt_firefighters + row.military_forces + row.other_forces , axis=1)
df['total_terrestrial_forces'] = df.apply(lambda row: row.Fire_trucks + row.other_fire_vehicles + row.fire_tankers + row.fire_equipent, axis=1)
df['total_aerial_forces'] = df.apply(lambda row: row.helicopters + row.fire_plane_type1 + row.fire_plane_type2 + row.fire_plane_type3 + row.fire_plane_type4, axis=1)

In [33]:
df.head()

,Fire_department,region,start_date,start_time,end_date,end_time,borough,burned_forests1,burned_forests2,burned_forests3,burned_fields,burned_swamp,burned_Agricultural,burned_Agricultural2,burned_garbage_disposal_sites,firefighters,firefighters2,volunt_firefighters,military_forces,other_forces,Fire_trucks,other_fire_vehicles,fire_tankers,fire_equipent,helicopters,fire_plane_type1,fire_plane_type2,fire_plane_type3,fire_plane_type4,extinguish_time,extinguish_date,total_burned_acres,total_firefight_personel,total_terrestrial_forces,total_aerial_forces
1,Π.Κ. ΚΑΛΑΜΟΥ,ΑΤΤΙΚΗΣ,2018-05-29,2019-07-17 12:06:00,2018-05-29,2019-07-17 18:30:00,Δ. ΩΡΩΠΟΥ,0,0,0,0,0,3,0,0,6,0,2,0,0,2,0,0,0,0,0,0,0,0,06:24:00,0,3.0,8,2,0
2,Π.Κ. ΚΑΛΑΜΟΥ,ΑΤΤΙΚΗΣ,2018-07-23,2019-07-17 19:00:00,2018-07-31,2019-07-17 10:18:00,Δ. ΩΡΩΠΟΥ,0,150,0,150,0,350,0,0,21,6,30,0,12,7,15,2,0,0,1,0,0,0,-1 days +15:18:00,8,650.0,69,24,1
3,Π.Κ. ΚΑΛΑΜΟΥ,ΑΤΤΙΚΗΣ,2018-08-26,2019-07-17 15:30:00,2018-08-27,2019-07-17 07:55:00,Δ. ΩΡΩΠΟΥ,0,0,0,0,0,0,0,0,15,1,26,0,0,4,0,0,0,0,1,0,0,0,-1 days +16:25:00,1,0.0,42,4,1
4,Π.Κ. ΚΑΛΑΜΟΥ,ΑΤΤΙΚΗΣ,2018-11-07,2019-07-17 20:10:00,2018-11-08,2019-07-17 21:10:00,Δ. ΩΡΩΠΟΥ,0,0,0,0,0,0,1,0,6,0,12,0,5,3,6,1,2,0,0,0,0,0,01:00:00,1,1.0,23,12,0
5,1ος Π.Σ. ΑΘΗΝΩΝ,ΑΤΤΙΚΗΣ,2018-05-23,2019-07-17 17:36:00,2018-05-23,2019-07-17 18:10:00,Δ. ΚΑΙΣΑΡΙΑΝΗΣ,0,10,0,0,0,0,0,0,13,0,10,0,0,5,4,0,0,0,0,0,0,0,00:34:00,0,10.0,23,9,0

In [34]:
df.shape

(6691, 35)

In [35]:
df = df.drop(columns=['burned_forests1',
                      'burned_forests2', 
                      'burned_forests3', 
                      'burned_fields',
                      'burned_swamp',
                      'burned_Agricultural',
                      'burned_Agricultural2',
                      'burned_garbage_disposal_sites',
                      'firefighters',
                      'firefighters2',
                      'volunt_firefighters',
                      'military_forces',
                      'other_forces', 
                      'Fire_trucks',
                      'other_fire_vehicles',
                      'fire_tankers',
                      'fire_equipent',
                      'helicopters',
                      'fire_plane_type1', 
                      'fire_plane_type2',
                      'fire_plane_type3',
                      'fire_plane_type4'])
df.head()

,Fire_department,region,start_date,start_time,end_date,end_time,borough,extinguish_time,extinguish_date,total_burned_acres,total_firefight_personel,total_terrestrial_forces,total_aerial_forces
1,Π.Κ. ΚΑΛΑΜΟΥ,ΑΤΤΙΚΗΣ,2018-05-29,2019-07-17 12:06:00,2018-05-29,2019-07-17 18:30:00,Δ. ΩΡΩΠΟΥ,06:24:00,0,3.0,8,2,0
2,Π.Κ. ΚΑΛΑΜΟΥ,ΑΤΤΙΚΗΣ,2018-07-23,2019-07-17 19:00:00,2018-07-31,2019-07-17 10:18:00,Δ. ΩΡΩΠΟΥ,-1 days +15:18:00,8,650.0,69,24,1
3,Π.Κ. ΚΑΛΑΜΟΥ,ΑΤΤΙΚΗΣ,2018-08-26,2019-07-17 15:30:00,2018-08-27,2019-07-17 07:55:00,Δ. ΩΡΩΠΟΥ,-1 days +16:25:00,1,0.0,42,4,1
4,Π.Κ. ΚΑΛΑΜΟΥ,ΑΤΤΙΚΗΣ,2018-11-07,2019-07-17 20:10:00,2018-11-08,2019-07-17 21:10:00,Δ. ΩΡΩΠΟΥ,01:00:00,1,1.0,23,12,0
5,1ος Π.Σ. ΑΘΗΝΩΝ,ΑΤΤΙΚΗΣ,2018-05-23,2019-07-17 17:36:00,2018-05-23,2019-07-17 18:10:00,Δ. ΚΑΙΣΑΡΙΑΝΗΣ,00:34:00,0,10.0,23,9,0

In [52]:
df.region.value_counts()

ΛΑΡΙΣΑΣ             519
ΜΕΣΣΗΝΙΑΣ           450
ΗΛΕΙΑΣ              425
ΑΙΤΩΛΟΑΚΑΡΝΑΝΙΑΣ    293
ΑΧΑΙΑΣ              264
ΚΙΛΚΙΣ              260
ΡΟΔΟΠΗΣ             249
ΚΑΡΔΙΤΣΑΣ           217
ΗΡΑΚΛΕΙΟΥ           211
ΠΕΛΛΑΣ              211
ΘΕΣΣΑΛΟΝΙΚΗΣ        198
ΕΥΒΟΙΑΣ             195
ΕΒΡΟΥ               180
ΚΕΡΚΥΡΑΣ            170
ΚΑΒΑΛΑΣ             160
ΚΕΦΑΛΛΟΝΙΑΣ         140
ΛΑΚΩΝΙΑΣ            137
ΠΙΕΡΙΑΣ             130
ΗΜΑΘΙΑΣ             128
ΑΤΤΙΚΗΣ             122
ΑΡΤΑΣ               117
ΞΑΝΘΗΣ              115
ΑΡΚΑΔΙΑΣ            113
ΡΕΘΥΜΝΟΥ            109
ΔΡΑΜΑΣ              105
ΒΟΙΩΤΙΑΣ            102
ΦΘΙΩΤΙΔΑΣ            99
ΛΕΣΒΟΥ               94
ΜΑΓΝΗΣΙΑΣ            93
ΚΥΚΛΑΔΩΝ             92
ΣΑΜΟΥ                84
ΤΡΙΚΑΛΩΝ             82
ΚΟΖΑΝΗΣ              74
ΘΕΣΠΡΩΤΙΑΣ           73
ΚΟΡΙΝΘΙΑΣ            71
ΣΕΡΡΩΝ               70
ΙΩΑΝΝΙΝΩΝ            69
ΔΩΔΕΚΑΝΗΣΩΝ          64
ΧΑΝΙΩΝ               59
ΖΑΚΥΝΘΟΥ             58
ΚΑΣΤΟΡΙΑΣ            56
ΠΡΕΒΕΖΗΣ             42
ΓΡΕΒΕΝΩΝ             39
ΛΑΣΙΘΙΟΥ             33
ΦΛΩΡΙΝΑΣ             32
ΛΕΥΚΑΔΟΣ             27
ΦΩΚΙΔΟΣ              25
ΧΙΟΥ                 20
ΧΑΛΚΙΔΙΚΗΣ           11
ΕΥΡΥΤΑΝΙΑΣ            3
ΑΡΓΟΛΙΔΟΣ             1
Name: region, dtype: int64

In [48]:
df.groupby('Fire_department').total_firefight_personel.value_counts()

Fire_department      total_firefight_personel
 1ος Π.Σ. ΑΘΗΝΩΝ     23                           1
 6ος Π.Σ. ΑΘΗΝΩΝ     5                            1
                     9                            1
                     10                           1
                     12                           1
                     18                           1
                     19                           1
                     22                           1
                     34                           1
                     48                           1
 8ος Π.Σ. ΑΘΗΝΩΝ     9                            1
                     12                           1
                     15                           1
 9ος Π.Σ. ΑΘΗΝΩΝ     24                           2
                     14                           1
                     20                           1
                     47                           1
                     62                           1
10ος Π.Σ. ΑΘΗΝΩΝ     4                            1
                     6                            1
                     9                            1
                     10                           1
                     32                           1
                     42                           1
12ος Π.Σ. ΑΘΗΝΩΝ     792                          1
1ος  Π.Σ. ΗΡΑΚΛΕΙΟΥ  3                           29
                     5                           21
                     2                           16
                     7                            5
                     9                            4
                                                 ..
Π.Υ. ΧΑΛΚΙΔΑΣ        10                           6
                     12                           6
                     9                            5
                     5                            4
                     14                           3
                     18                           3
                     7                            2
                     11                           2
                     15                           2
                     13                           1
                     21                           1
                     30                           1
                     32                           1
                     34                           1
                     71                           1
                     84                           1
                     141                          1
                     599                          1
Π.Υ. ΧΙΟΥ            4                            2
                     6                            1
                     7                            1
                     12                           1
                     15                           1
                     20                           1
Π.Υ. ΧΡΥΣΟΥΠΟΛΗΣ     0                           51
                     2                           20
                     3                            1
                     4                            1
                     6                            1
                     10                           1
Name: total_firefight_personel, Length: 1766, dtype: int64

In [50]:
df.sort_values(by ='total_burned_acres', ascending=False).head(5)

,Fire_department,region,start_date,start_time,end_date,end_time,borough,extinguish_time,extinguish_date,total_burned_acres,total_firefight_personel,total_terrestrial_forces,total_aerial_forces
41,Π.Υ. ΜΕΓΑΡΩΝ,ΑΤΤΙΚΗΣ,2018-07-23,2019-07-17 12:03:00,2018-08-02,2019-07-17 19:30:00,Δ. ΜΕΓΑΡΕΩΝ,07:27:00,10,50650.0,117,53,28
31,12ος Π.Σ. ΑΘΗΝΩΝ,ΑΤΤΙΚΗΣ,2018-07-23,2019-07-17 16:49:00,2018-09-10,2019-07-17 09:04:00,Δ. ΠΕΝΤΕΛΗΣ,-1 days +16:15:00,49,12500.0,792,84,0
6065,Π.Υ. ΣΥΚΙΩΝΟΣ - ΚΙΑΤΟΥ,ΚΟΡΙΝΘΙΑΣ,2018-07-23,2019-07-17 17:20:00,2018-08-02,2019-07-17 20:00:00,Δ. ΞΥΛΟΚΑΣΤΡΟΥ-ΕΥΡΩΣΤΙΝΗΣ,02:40:00,10,10000.0,218,38,9
6409,Π.Υ. ΧΑΛΚΙΔΑΣ,ΕΥΒΟΙΑΣ,2018-08-12,2019-07-17 15:07:00,2018-08-21,2019-07-17 20:38:00,Δ. ΔΙΡΦΥΩΝ - ΜΕΣΣΑΠΙΩΝ,05:31:00,9,5800.0,599,118,12
6605,Π.Κ. ΠΑΡΟΥ,ΚΥΚΛΑΔΩΝ,2018-07-31,2019-07-17 16:42:00,2018-08-09,2019-07-17 07:50:00,Δ. ΠΑΡΟΥ,-1 days +15:08:00,9,4000.0,79,17,4

In [51]:
df.sort_values(by ='Fire_department', ascending=False).head(5)

,Fire_department,region,start_date,start_time,end_date,end_time,borough,extinguish_time,extinguish_date,total_burned_acres,total_firefight_personel,total_terrestrial_forces,total_aerial_forces
469,Π.Υ. ΧΡΥΣΟΥΠΟΛΗΣ,ΚΑΒΑΛΑΣ,2018-01-26,2019-07-17 14:59:00,2018-01-26,2019-07-17 15:25:00,Δ. ΝΕΣΤΟΥ,00:26:00,0,0.0,2,1,0
516,Π.Υ. ΧΡΥΣΟΥΠΟΛΗΣ,ΚΑΒΑΛΑΣ,2018-08-04,2019-07-17 13:30:00,2018-08-04,2019-07-17 18:38:00,Δ. ΝΕΣΤΟΥ,05:08:00,0,40.0,6,3,2
523,Π.Υ. ΧΡΥΣΟΥΠΟΛΗΣ,ΚΑΒΑΛΑΣ,2018-09-02,2019-07-17 17:55:00,2018-09-02,2019-07-17 18:51:00,Δ. ΝΕΣΤΟΥ,00:56:00,0,12.0,2,1,0
522,Π.Υ. ΧΡΥΣΟΥΠΟΛΗΣ,ΚΑΒΑΛΑΣ,2018-09-02,2019-07-17 14:55:00,2018-09-02,2019-07-17 16:24:00,Δ. ΝΕΣΤΟΥ,01:29:00,0,2.0,4,2,0
521,Π.Υ. ΧΡΥΣΟΥΠΟΛΗΣ,ΚΑΒΑΛΑΣ,2018-08-29,2019-07-17 16:40:00,2018-08-29,2019-07-17 17:00:00,Δ. ΝΕΣΤΟΥ,00:20:00,0,0.0,0,0,0