In [1]:
%matplotlib inline

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
pd.set_option("display.max_columns", 100)

In [4]:
df1 = pd.read_excel('/Users/kosmas/Desktop/Columbia_Data_Studio_Projects/data-studio-projects/Weekly projects/Traffic_violations_in_Greece /troxaia2015paravaseis.xls')
df1.head()

,Α.Ε.Α. - ΔΙΕΘΥΝΣΗ ΤΡΟΧΑΙΑΣ ΑΣΤΥΝΟΜΕΥΣΗΣ,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,NaN,NaN,NaN,NaN,NaN
1,Πίνακας επικίνδυνων παραβάσεων\n ΕΤΟΥΣ 2015-2014,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN
3,ΕΙΔΟΣ ΠΑΡΑΒΑΣΗΣ,2015.0,2014.0,ΔΙΑΦΟΡΑ,ΠΟΣΟΣΤΟ
4,Παραβίαση προτεραιότητας,3927.0,3836.0,91,0.0237226

In [5]:
df1 = df1.drop(['Unnamed: 3','Unnamed: 4'], axis = 1)

In [6]:
df1 = df1.drop([0,1,2,3])

In [7]:
df1 = df1.rename(index=str, columns={'Α.Ε.Α. - ΔΙΕΘΥΝΣΗ ΤΡΟΧΑΙΑΣ ΑΣΤΥΝΟΜΕΥΣΗΣ': 'ΕΙΔΟΣ_ΠΑΡΑΒΑΣΗΣ_',
                                   'Unnamed: 1': '2015',
                                   'Unnamed: 2': '2014'})
df1.head()

                ΕΙΔΟΣ_ΠΑΡΑΒΑΣΗΣ_     2015     2014
4      Παραβίαση προτεραιότητας    3927.0   3836.0
5  Παραβίαση ερυθρού Σηματοδότη   14564.0  13913.0
6          Αντικανονικοί ελιγμοί   5926.0   5137.0
7     Κίνηση στο αντίθετο ρεύμα   11695.0  12729.0
8      Αντικανονικό Προσπέρασμα    8406.0   8107.0

In [8]:
df1 = df1.reset_index()

In [9]:
df1 = df1.drop(columns=['index'])

In [10]:
df1 = df1.astype({"2015": int, "2014": int})

In [11]:
df1

                                     ΕΙΔΟΣ_ΠΑΡΑΒΑΣΗΣ_    2015    2014
0                           Παραβίαση προτεραιότητας     3927    3836
1                       Παραβίαση ερυθρού Σηματοδότη    14564   13913
2                               Αντικανονικοί ελιγμοί    5926    5137
3                          Κίνηση στο αντίθετο ρεύμα    11695   12729
4                           Αντικανονικό Προσπέρασμα     8406    8107
5   Κίνηση στην αριστερή λωρίδα - Μη κίνηση στο άκ...     261     297
6                           Μη χρήση ζώνης ασφαλείας    29611   34526
7                        Μη χρήση παιδικών καθισμάτων     424     626
8                                   Μη χρήση κράνους    52783   54354
9                         Παραβάσεις οχημάτων (ΚΤΕΟ)    25130   30683
10                             Παραβάσεις \nταχύτητας  173476  156892
11                 Παραβίαση χρήσης κινητού τηλεφώνου   19730   23459
12                                 Φθαρμένα ελαστικά     5177    5744
13                 Παραβάσεις διαφημιστικών πινακίδων    3266    2461
14                                               Μέθη   29191   29597
15                                 ΣΥΝΟΛΟ ΠΑΡΑΒΑΣΕΩΝ   383567  382361

In [12]:
df2 = pd.read_excel('/Users/kosmas/Desktop/Columbia_Data_Studio_Projects/data-studio-projects/Weekly projects/Traffic_violations_in_Greece /troxaia2016_paravaseis.xls')
df2.head()

,Α.Ε.Α. - ΔΙΕΘΥΝΣΗ ΤΡΟΧΑΙΑΣ ΑΣΤΥΝΟΜΕΥΣΗΣ,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,NaN,NaN,NaN,NaN,NaN
1,Πίνακας επικίνδυνων παραβάσεων\n έτους 2016-2015,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN
3,ΕΙΔΟΣ ΠΑΡΑΒΑΣΗΣ,2016.0,2015.0,ΔΙΑΦΟΡΑ,ΠΟΣΟΣΤΟ
4,Παραβίαση προτεραιότητας,3733.0,3927.0,-194,-0.0494016

In [13]:
df2 = df2.drop(['Unnamed: 3','Unnamed: 2','Unnamed: 4'], axis = 1)

In [14]:
df2 = df2.drop([0,1,2,3,20])

In [15]:
df2 = df2.rename(index=str, columns={'Α.Ε.Α. - ΔΙΕΘΥΝΣΗ ΤΡΟΧΑΙΑΣ ΑΣΤΥΝΟΜΕΥΣΗΣ': 'ΕΙΔΟΣ_ΠΑΡΑΒΑΣΗΣ1',
                                   'Unnamed: 1': '2016'})

In [16]:
df2 = df2.reset_index()

In [17]:
df2 = df2.astype({"2016": int})

In [18]:
df2 = df2.drop(columns=['index'])

In [19]:
df2

                                     ΕΙΔΟΣ_ΠΑΡΑΒΑΣΗΣ1    2016
0                           Παραβίαση προτεραιότητας     3733
1                       Παραβίαση ερυθρού Σηματοδότη    16152
2                               Αντικανονικοί ελιγμοί    6348
3                          Κίνηση στο αντίθετο ρεύμα    12329
4                           Αντικανονικό Προσπέρασμα    10042
5   Κίνηση στην αριστερή λωρίδα - Μη κίνηση στο άκ...     366
6                           Μη χρήση ζώνης ασφαλείας    34831
7                        Μη χρήση παιδικών καθισμάτων     613
8                                   Μη χρήση κράνους    63971
9                         Παραβάσεις οχημάτων (ΚΤΕΟ)    18238
10                             Παραβάσεις \nταχύτητας  176592
11                 Παραβίαση χρήσης κινητού τηλεφώνου   25381
12                                 Φθαρμένα ελαστικά     5140
13                 Παραβάσεις διαφημιστικών πινακίδων    2728
14                                               Μέθη   33192
15                                 ΣΥΝΟΛΟ ΠΑΡΑΒΑΣΕΩΝ   409656

In [20]:
df3 = pd.read_excel('/Users/kosmas/Desktop/Columbia_Data_Studio_Projects/data-studio-projects/Weekly projects/Traffic_violations_in_Greece /troxaia-2017_paravaseis.xls')
df3.head()

,Α.Ε.Α. - ΔΙΕΘΥΝΣΗ ΤΡΟΧΑΙΑΣ ΑΣΤΥΝΟΜΕΥΣΗΣ,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,NaN,NaN,NaN,NaN,NaN
1,Πίνακας επικίνδυνων παραβάσεων\n ΕΤΟΥΣ 2017-2016,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN
3,ΕΙΔΟΣ ΠΑΡΑΒΑΣΗΣ,2017.0,2016.0,ΔΙΑΦΟΡΑ,ΠΟΣΟΣΤΟ
4,Παραβίαση προτεραιότητας,2977.0,3733.0,-756,-0.202518

In [21]:
df3 = df3.drop(['Unnamed: 2','Unnamed: 3','Unnamed: 4'], axis = 1)

In [22]:
df3 = df3.drop([0,1,2,3])

In [23]:
df3 = df3.rename(index=str, columns={'Α.Ε.Α. - ΔΙΕΘΥΝΣΗ ΤΡΟΧΑΙΑΣ ΑΣΤΥΝΟΜΕΥΣΗΣ': 'ΕΙΔΟΣ_ΠΑΡΑΒΑΣΗΣ2',
                                   'Unnamed: 1': '2017'})

In [24]:
df3 = df3.reset_index()

In [25]:
df3 = df3.astype({"2017": int})

In [26]:
df3 = df3.drop(columns=['index'])

In [27]:
df3

                      ΕΙΔΟΣ_ΠΑΡΑΒΑΣΗΣ2    2017
0            Παραβίαση προτεραιότητας     2977
1        Παραβίαση ερυθρού Σηματοδότη    15501
2                Αντικανονικοί ελιγμοί    6860
3           Κίνηση στο αντίθετο ρεύμα    11921
4            Αντικανονικό Προσπέρασμα     7638
5         Κίνηση στην αριστερή λωρίδα      448
6            Μη χρήση ζώνης ασφαλείας    32500
7         Μη χρήση παιδικών καθισμάτων     876
8                    Μη χρήση κράνους    60142
9          Παραβάσεις οχημάτων (ΚΤΕΟ)    19309
10              Παραβάσεις \nταχύτητας  214132
11  Παραβίαση χρήσης κινητού τηλεφώνου   24127
12                  Φθαρμένα ελαστικά     5774
13  Παραβάσεις διαφημιστικών πινακίδων    3440
14                                Μέθη   33620
15                  ΣΥΝΟΛΟ ΠΑΡΑΒΑΣΕΩΝ   439265

In [28]:
df4 = pd.read_excel('/Users/kosmas/Desktop/Columbia_Data_Studio_Projects/data-studio-projects/Weekly projects/Traffic_violations_in_Greece /troxaia-2018_paravaseis.xls')
df4.head()

,Α.Ε.Α. - ΔΙΕΘΥΝΣΗ ΤΡΟΧΑΙΑΣ ΑΣΤΥΝΟΜΕΥΣΗΣ,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,NaN,NaN,NaN,NaN,NaN
1,Πίνακας επικίνδυνων παραβάσεων\n ΕΤΟΥΣ 2018-2017,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN
3,ΕΙΔΟΣ ΠΑΡΑΒΑΣΗΣ,2018.0,2017.0,ΔΙΑΦΟΡΑ,ΠΟΣΟΣΤΟ
4,Παραβίαση προτεραιότητας,2270.0,2928.0,-658,-0.224727

In [29]:
df4 = df4.drop(['Unnamed: 2','Unnamed: 3','Unnamed: 4'], axis = 1)

In [30]:
df4 = df4.drop([0,1,2,3])

In [31]:
df4 = df4.rename(index=str, columns={'Α.Ε.Α. - ΔΙΕΘΥΝΣΗ ΤΡΟΧΑΙΑΣ ΑΣΤΥΝΟΜΕΥΣΗΣ': 'ΕΙΔΟΣ_ΠΑΡΑΒΑΣΗΣ3',
                                   'Unnamed: 1': '2018'})

In [32]:
df4 = df4.reset_index()

In [33]:
df4 = df4.astype({"2018": int})

In [34]:
df4 = df4.drop(columns=['index'])

In [35]:
df4

                                     ΕΙΔΟΣ_ΠΑΡΑΒΑΣΗΣ3    2018
0                           Παραβίαση προτεραιότητας     2270
1                       Παραβίαση ερυθρού Σηματοδότη    14931
2                               Αντικανονικοί ελιγμοί    4593
3                          Κίνηση στο αντίθετο ρεύμα    11364
4                           Αντικανονικό Προσπέρασμα     6706
5   Κίνηση στην αριστερή λωρίδα - Μη κίνηση στο άκ...     310
6                           Μη χρήση ζώνης ασφαλείας    33380
7                        Μη χρήση παιδικών καθισμάτων     920
8                                   Μη χρήση κράνους    52706
9                         Παραβάσεις οχημάτων (ΚΤΕΟ)    25845
10                               Παραβάσεις ταχύτητας  213333
11                 Παραβίαση χρήσης κινητού τηλεφώνου   18224
12                                 Φθαρμένα ελαστικά     5785
13                 Παραβάσεις διαφημιστικών πινακίδων    3165
14                                               Μέθη   33394
15                                 ΣΥΝΟΛΟ ΠΑΡΑΒΑΣΕΩΝ   426926

In [36]:
df = pd.concat([df1, df2, df3, df4], axis=1, sort=False)

In [37]:
df = df.drop(columns=['ΕΙΔΟΣ_ΠΑΡΑΒΑΣΗΣ1', 'ΕΙΔΟΣ_ΠΑΡΑΒΑΣΗΣ2', 'ΕΙΔΟΣ_ΠΑΡΑΒΑΣΗΣ3'])

In [38]:
df = df[['ΕΙΔΟΣ_ΠΑΡΑΒΑΣΗΣ_', '2014', '2015', '2016', '2017', '2018']]

In [39]:
df = df.drop([15])

In [40]:
df.head()

                ΕΙΔΟΣ_ΠΑΡΑΒΑΣΗΣ_   2014   2015   2016   2017   2018
0      Παραβίαση προτεραιότητας    3836   3927   3733   2977   2270
1  Παραβίαση ερυθρού Σηματοδότη   13913  14564  16152  15501  14931
2          Αντικανονικοί ελιγμοί   5137   5926   6348   6860   4593
3     Κίνηση στο αντίθετο ρεύμα   12729  11695  12329  11921  11364
4      Αντικανονικό Προσπέρασμα    8107   8406  10042   7638   6706

In [41]:
df.shape

(15, 6)

In [42]:
df.dtypes

ΕΙΔΟΣ_ΠΑΡΑΒΑΣΗΣ_    object
2014                 int64
2015                 int64
2016                 int64
2017                 int64
2018                 int64
dtype: object

In [43]:
df.to_csv('final_violations.csv')

In [51]:
df = pd.read_csv('/Users/kosmas/Desktop/Columbia_Data_Studio_Projects/data-studio-projects/Weekly projects/Traffic_violations_in_Greece /final_violations.csv')
df

,Unnamed: 0,ΕΙΔΟΣ_ΠΑΡΑΒΑΣΗΣ_,2014,2015,2016,2017,2018
0,0,Παραβίαση προτεραιότητας,3836,3927,3733,2977,2270
1,1,Παραβίαση ερυθρού Σηματοδότη,13913,14564,16152,15501,14931
2,2,Αντικανονικοί ελιγμοί,5137,5926,6348,6860,4593
3,3,Κίνηση στο αντίθετο ρεύμα,12729,11695,12329,11921,11364
4,4,Αντικανονικό Προσπέρασμα,8107,8406,10042,7638,6706
5,5,Κίνηση στην αριστερή λωρίδα,297,261,366,448,310
6,6,Μη χρήση ζώνης ασφαλείας,34526,29611,34831,32500,33380
7,7,Μη χρήση παιδικών καθισμάτων,626,424,613,876,920
8,8,Μη χρήση κράνους,54354,52783,63971,60142,52706
9,9,Παραβάσεις οχημάτων (ΚΤΕΟ),30683,25130,18238,19309,25845
10,10,Παραβάσεις ταχύτητας,156892,173476,176592,214132,213333
11,11,Παραβίαση χρήσης κινητού τηλεφώνου,23459,19730,25381,24127,18224
12,12,Φθαρμένα ελαστικά,5744,5177,5140,5774,5785
13,13,Παραβάσεις διαφημιστικών πινακίδων,2461,3266,2728,3440,3165
14,14,Μέθη,29597,29191,33192,33620,33394

In [52]:
df = df.drop(columns=['Unnamed: 0'])

## This is my final dataframe

In [53]:
df

                      ΕΙΔΟΣ_ΠΑΡΑΒΑΣΗΣ_    2014    2015    2016    2017    2018
0             Παραβίαση προτεραιότητας    3836    3927    3733    2977    2270
1         Παραβίαση ερυθρού Σηματοδότη   13913   14564   16152   15501   14931
2                Αντικανονικοί ελιγμοί    5137    5926    6348    6860    4593
3            Κίνηση στο αντίθετο ρεύμα   12729   11695   12329   11921   11364
4             Αντικανονικό Προσπέρασμα    8107    8406   10042    7638    6706
5          Κίνηση στην αριστερή λωρίδα     297     261     366     448     310
6             Μη χρήση ζώνης ασφαλείας   34526   29611   34831   32500   33380
7         Μη χρήση παιδικών καθισμάτων     626     424     613     876     920
8                     Μη χρήση κράνους   54354   52783   63971   60142   52706
9          Παραβάσεις οχημάτων (ΚΤΕΟ)    30683   25130   18238   19309   25845
10                Παραβάσεις ταχύτητας  156892  173476  176592  214132  213333
11  Παραβίαση χρήσης κινητού τηλεφώνου   23459   19730   25381   24127   18224
12                   Φθαρμένα ελαστικά    5744    5177    5140    5774    5785
13  Παραβάσεις διαφημιστικών πινακίδων    2461    3266    2728    3440    3165
14                                Μέθη   29597   29191   33192   33620   33394

In [54]:
df.shape

(15, 6)

In [55]:
df.dtypes

ΕΙΔΟΣ_ΠΑΡΑΒΑΣΗΣ_    object
2014                 int64
2015                 int64
2016                 int64
2017                 int64
2018                 int64
dtype: object