In [1]:
import pandas as pd

In [27]:
df = pd.read_csv('/Users/kosmas/Desktop/Columbia_Data_Studio_Projects/data-studio-projects/Weekly projects/Fires_in Greece/970c9267-5b4e-424b-9092-91bc919d4c8b.csv', encoding='UTF-8')
df.head()

,FID,ESYE_ID,GREEKNAME,PREF_ID,PREFECTURE,EDRA,the_geom
0,970c9267-5b4e-424b-9092-91bc919d4c8b.0,42160000,ΛΙΒΑΔΙΟΥ,42,Ν. ΛΑΡΙΣΑΣ,ΛΙΒΑΔΙ,MULTIPOLYGON (((345534.05923610553 4450741.999...
1,970c9267-5b4e-424b-9092-91bc919d4c8b.1,42220000,ΟΛΥΜΠΟΥ,42,Ν. ΛΑΡΙΣΑΣ,ΚΑΛΛΙΘΕΑ,MULTIPOLYGON (((357296.50131980306 4448098.500...
2,970c9267-5b4e-424b-9092-91bc919d4c8b.5,98690000,ΔΡΟΣΙΑΣ,98,Ν. ΑΝΑΤΟΛΙΚΗΣ ΑΤΤΙΚΗΣ,ΔΡΟΣΙΑ,MULTIPOLYGON (((488545.59262545547 4217704.002...
3,970c9267-5b4e-424b-9092-91bc919d4c8b.343,71060000,ΟΡΕΣΤΙΑΔΟΣ,71,Ν. ΕΒΡΟΥ,ΟΡΕΣΤΙΑΔΑ,MULTIPOLYGON (((698833.3759813095 4604653.0014...
4,970c9267-5b4e-424b-9092-91bc919d4c8b.344,71070000,ΟΡΦΕΑ,71,Ν. ΕΒΡΟΥ,ΛΑΒΑΡΑ,MULTIPOLYGON (((681977.1884688777 4582442.9990...

In [33]:
df[['ESYE_ID', 'PREFECTURE']]

       ESYE_ID             PREFECTURE
0     42160000             Ν. ΛΑΡΙΣΑΣ
1     42220000             Ν. ΛΑΡΙΣΑΣ
2     98690000  Ν. ΑΝΑΤΟΛΙΚΗΣ ΑΤΤΙΚΗΣ
3     71060000               Ν. ΕΒΡΟΥ
4     71070000               Ν. ΕΒΡΟΥ
5     42630000             Ν. ΛΑΡΙΣΑΣ
6     61010000             Ν. ΠΙΕΡΙΑΣ
7     81100000         Ν. ΔΩΔΕΚΑΝΗΣΩΝ
8     81150000         Ν. ΔΩΔΕΚΑΝΗΣΩΝ
9     81160000         Ν. ΔΩΔΕΚΑΝΗΣΩΝ
10    81210000         Ν. ΔΩΔΕΚΑΝΗΣΩΝ
11    81610000         Ν. ΔΩΔΕΚΑΝΗΣΩΝ
12    84010000               Ν. ΣΑΜΟΥ
13    61020000             Ν. ΠΙΕΡΙΑΣ
14    98720000  Ν. ΑΝΑΤΟΛΙΚΗΣ ΑΤΤΙΚΗΣ
15    98800000  Ν. ΑΝΑΤΟΛΙΚΗΣ ΑΤΤΙΚΗΣ
16    96020000  Ν. ΠΕΙΡΑΙΩΣ ΚΑΙ ΝΗΣΩΝ
17    98730000  Ν. ΑΝΑΤΟΛΙΚΗΣ ΑΤΤΙΚΗΣ
18    98740000  Ν. ΑΝΑΤΟΛΙΚΗΣ ΑΤΤΙΚΗΣ
19    98810000  Ν. ΑΝΑΤΟΛΙΚΗΣ ΑΤΤΙΚΗΣ
20    98780000  Ν. ΑΝΑΤΟΛΙΚΗΣ ΑΤΤΙΚΗΣ
21    98790000  Ν. ΑΝΑΤΟΛΙΚΗΣ ΑΤΤΙΚΗΣ
22    99420000              Ν. ΑΘΗΝΩΝ
23    98820000  Ν. ΑΝΑΤΟΛΙΚΗΣ ΑΤΤΙΚΗΣ
24    98840000  Ν. ΑΝΑΤΟΛΙΚΗΣ ΑΤΤΙΚΗΣ
25    99030000              Ν. ΑΘΗΝΩΝ
26    99080000              Ν. ΑΘΗΝΩΝ
27     3610000            Ν. ΒΟΙΩΤΙΑΣ
28    99280000              Ν. ΑΘΗΝΩΝ
29     3620000            Ν. ΒΟΙΩΤΙΑΣ
...        ...                    ...
1005  83010000              Ν. ΛΕΣΒΟΥ
1006  83050000              Ν. ΛΕΣΒΟΥ
1007  44180000            Ν. ΤΡΙΚΑΛΩΝ
1008  44190000            Ν. ΤΡΙΚΑΛΩΝ
1009  44200000            Ν. ΤΡΙΚΑΛΩΝ
1010  44210000            Ν. ΤΡΙΚΑΛΩΝ
1011  22010000            Ν. ΚΕΡΚΥΡΑΣ
1012  83100000              Ν. ΛΕΣΒΟΥ
1013  22020000            Ν. ΚΕΡΚΥΡΑΣ
1014  22030000            Ν. ΚΕΡΚΥΡΑΣ
1015  22040000            Ν. ΚΕΡΚΥΡΑΣ
1016  22050000            Ν. ΚΕΡΚΥΡΑΣ
1017  22060000            Ν. ΚΕΡΚΥΡΑΣ
1018  22070000            Ν. ΚΕΡΚΥΡΑΣ
1019  22090000            Ν. ΚΕΡΚΥΡΑΣ
1020  22100000            Ν. ΚΕΡΚΥΡΑΣ
1021  22120000            Ν. ΚΕΡΚΥΡΑΣ
1022  22130000            Ν. ΚΕΡΚΥΡΑΣ
1023  22610000            Ν. ΚΕΡΚΥΡΑΣ
1024  83020000              Ν. ΛΕΣΒΟΥ
1025  83060000              Ν. ΛΕΣΒΟΥ
1026  83070000              Ν. ΛΕΣΒΟΥ
1027  83080000              Ν. ΛΕΣΒΟΥ
1028  83090000              Ν. ΛΕΣΒΟΥ
1029  83110000              Ν. ΛΕΣΒΟΥ
1030  83150000              Ν. ΛΕΣΒΟΥ
1031  83160000              Ν. ΛΕΣΒΟΥ
1032  83170000              Ν. ΛΕΣΒΟΥ
1033   1100000    Ν. ΑΙΤΩΛΟΑΚΑΡΝΑΝΙΑΣ
1034   1010000    Ν. ΑΙΤΩΛΟΑΚΑΡΝΑΝΙΑΣ

[1035 rows x 2 columns]

In [34]:
df[['ESYE_ID', 'PREFECTURE']].to_csv('greek_labels.csv')

In [35]:
df.dtypes

FID           object
ESYE_ID        int64
GREEKNAME     object
PREF_ID        int64
PREFECTURE    object
EDRA          object
the_geom      object
dtype: object